### ISSUE TITLE
Can't add spawns

### ISSUE THREAD

**Issue by R0dr1G02M4R5** [TheTurkeyDev/Call_Of_Minecraft-Zombies#121]
Hi.
So I am trying to add the spawns to the map but it won't let me. I can do /z editspawns arena and afterwards done but when i write add it gives this error:
```
[00:00:00] [Server thread/WARN]: [COM_Zombies] Task #26654 for COM_Zombies v2.3.112 generated an exception
java.lang.NullPointerException: Cannot invoke "com.theprogrammingturkey.comz.game.Arena.containsBlock(org.bukkit.Location)" because "this.game.arena" is null
	at com.theprogrammingturkey.comz.game.actions.SpawnsEditAction.onChatMessage(SpawnsEditAction.java:41) ~[?:?]
	at com.theprogrammingturkey.comz.listeners.PlayerChatListener.lambda$onPlayerChat$1(PlayerChatListener.java:39) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
Thanks!

**Comment by TheTurkeyDev** [comment]
Not sure why I didn't see this issue till now, but seems your arena is stuck in a weird state. Try restarting your server and if that doesn't work delete the arena and try again.

**Comment by CoolGunner** [comment]
did you setup your map right for the p1 and p2 ?idk if this got fixed or not but if not sit p1 at bedrock and then go up to 255 and set p2 and then adding spawn should work :)
