### ISSUE TITLE
Unable to complete server set up

### ISSUE THREAD

**Issue by aromaticcactus** [TheTurkeyDev/Call_Of_Minecraft-Zombies#122]
After I set p1, p2, gw, lw, and sw, I cannot complete the set up by typing done. When I try to do so, nothing happens. The text doesn't pop up in chat, and im still in set up mode.
If i type cancel, it will cancel the set up. Not sure why that is.

**Comment by aromaticcactus** [comment]
java.lang.NullPointerException: Cannot invoke "com.theprogrammingturkey.comz.spawning.SpawnPoint.getID()" because "spawnPoint" is null
	at com.theprogrammingturkey.comz.game.managers.BarrierManager.lambda$save$1(BarrierManager.java:100) ~[comzombies-Universal-2.3.124.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.theprogrammingturkey.comz.game.managers.BarrierManager.save(BarrierManager.java:100) ~[comzombies-Universal-2.3.124.jar:?]
	at com.theprogrammingturkey.comz.game.Game.saveGame(Game.java:994) ~[comzombies-Universal-2.3.124.jar:?]
	at com.theprogrammingturkey.comz.game.GameManager.saveAllGames(GameManager.java:78) ~[comzombies-Universal-2.3.124.jar:?]
	at com.theprogrammingturkey.comz.game.Game.gameSetupComplete(Game.java:1353) ~[comzombies-Universal-2.3.124.jar:?]
	at com.theprogrammingturkey.comz.game.actions.ArenaSetupAction.onChatMessage(ArenaSetupAction.java:84) ~[comzombies-Universal-2.3.124.jar:?]
	at com.theprogrammingturkey.comz.listeners.PlayerChatListener.lambda$onPlayerChat$1(PlayerChatListener.java:39) ~[comzombies-Universal-2.3.124.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-177]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-177]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TheTurkeyDev** [comment]
Seems you have somehow created a bugged barrier. Is this the first arena you've attempted to make?

**Comment by aromaticcactus** [comment]
This is the second arena I've created.
Would you suggest I delete the barriers from my first arena?

**Comment by TheTurkeyDev** [comment]
If you can. That's where the issue is currently. Not sure how this has happened

**Comment by aromaticcactus** [comment]
Just removed all the barriers from my previous arena, it fixed the issue.
The only thing I can think of that may have affected this issue is that I set the barrier sign on an already existing sign, so that the barrier sign was floating in front of the preexisting sign.

**Comment by aromaticcactus** [comment]
Worth noting that the sign on a sign did not affect the barrier in-game, it functioned normally

**Comment by TheTurkeyDev** [comment]
Hmmm Interesting. glad that fixed it for you though!
