### ISSUE TITLE
Player spawn point not working

### ISSUE THREAD

**Issue by TheTClass** [TheTurkeyDev/Call_Of_Minecraft-Zombies#126]
I've just made a map for the 1.16.5 version of the plugin but the player spawn doesn't seem to be working. I have used "/z edit Kino" then typed "gw" at the spawn, then typed done. When you attempt to join, the lobby works fine, but once you get in the game it gives me the message:
"Well.. I guess we had an error trying to pick a spawn point out of the many we had! We'll have to end your game because of our lack of skillez."
I'm not sure if a ender portal frame is suppose to spawn for the player spawns but it isn't when I'm typing "gw". [Here is a link to a video showing this happening](https://youtu.be/M-NPpNt6hsg)
This warn is also appearing after the game starts:

[21:22:41] [Server thread/WARN]: [COM_Zombies] Task #225 for COM_Zombies v2.2.86 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_311]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_311]
        at com.theprogrammingturkey.comz.spawning.SpawnManager.smartSpawn(SpawnManager.java:250) ~[?:?]
        at com.theprogrammingturkey.comz.spawning.SpawnManager.startWave(SpawnManager.java:403) ~[?:?]
        at com.theprogrammingturkey.comz.game.Game.lambda$nextWave$0(Game.java:571) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1179) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]

**Comment by TheTurkeyDev** [comment]
It seems you have no zombie spawnpoints set? Did you add any?

**Comment by TheTClass** [comment]
> 

I did set the zombie spawnpoints. I just re-did them and it works now, thanks.
