### ISSUE TITLE
power no work

### ISSUE THREAD

**Issue by frogglen** [TheTurkeyDev/Call_Of_Minecraft-Zombies#141]
the electricity doesn't seem to be working, I create a sign with the requirements but nothing happens, in the console it appears that the power is now off and then I try to use a zombie command and the plugin stops working. 

```
[04:46:27] [Server thread/INFO]: FrogGlen issued server command: /z help admin 2
[04:46:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'z' in plugin COM_Zombies v2.3.DEV
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:920) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2382) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2342) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/theprogrammingturkey/comz/commands/ZombiesHelpCommand
	at com.theprogrammingturkey.comz.commands.CommandManager.onCommand(CommandManager.java:256) ~[comzombies-Universal-2.3.DEV.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.theprogrammingturkey.comz.commands.ZombiesHelpCommand
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at com.theprogrammingturkey.comz.commands.CommandManager.onCommand(CommandManager.java:256) ~[comzombies-Universal-2.3.DEV.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by TheTurkeyDev** [comment]
Something seems broken with your setup. Typically you only see
`java.lang.NoClassDefFoundError: com/theprogrammingturkey/comz/commands/ZombiesHelpCommand` when the jar file is corrupted or has been loaded in wrong. Can your provide more information about your sever setup and if there are any errors when your server first starts?

**Comment by frogglen** [comment]
> Something seems broken with your setup. Typically you only see `java.lang.NoClassDefFoundError: com/theprogrammingturkey/comz/commands/ZombiesHelpCommand` when the jar file is corrupted or has been loaded in wrong. Can your provide more information about your sever setup and if there are any errors when your server first starts?

sorry for taking so long to answer, I compiled the jar file with intelliJ and translated it to spanish, I only changed the texts to spanish, I am using purpur 1.19.4.

**Comment by frogglen** [comment]
I don't have any error when starting the server, in fact the plugin works fine, only the electricity doesn't seem to work.

**Comment by TheTurkeyDev** [comment]
I've never tested this on purpur , so I can't guarantee it's compatible there. Beyond that though, sounds like your jar didn't compile correct then if you are getting missing classes.

As far as power goes, it's always been a bit half baked and not fully implemented. I honestly can't remember the full scope of where it's at
