### ISSUE TITLE
Paper server issues

### ISSUE THREAD

**Issue by TheTurkeyDev** [TheTurkeyDev/Call_Of_Minecraft-Zombies#162]

**Comment by Dallasp95** [comment]
![error1](https://github.com/user-attachments/assets/4a0876af-ef53-4a88-9ede-73775136e5ee)
![error1 5](https://github.com/user-attachments/assets/2fdba9f7-b374-4293-8c6a-1604a6eea7d6)

**Comment by Dallasp95** [comment]
it does this issue for anything, once the problem starts.  i cant edit an already existing arena,  make a new one,  edit spawns, i get completly locked out. 
![image_2024-12-23_155757485](https://github.com/user-attachments/assets/8f8fa13a-d01b-446b-bf60-4aac06101260)

**Comment by TheTurkeyDev** [comment]
Is there any chance you can upload your full server logs to like pastebin or something and send them here?

**Comment by Dallasp95** [comment]
> Is there any chance you can upload your full server logs to like pastebin or something and send them here?

am i suppose to do separate posts on there for each one? or put them all into one "paste". separated by a line or somthing

**Comment by TheTurkeyDev** [comment]
Separate posts if you can

**Comment by Dallasp95** [comment]
That might take abit with 50 different logs haha. Give me a bit. Still
learning how this website works, and how to make it so only you can see them

**Comment by Dallasp95** [comment]
unless you only want todays log

**Comment by TheTurkeyDev** [comment]
Realistically I just want the server startup and then the errors with like 10 lines before and after the error

**Comment by Dallasp95** [comment]
> Realistically I just want the server startup and then the errors with like 10 lines before and after the error

https://pastebin.com/T5dF4pg2

message me on discord for the password  (i cant message you first)

**Comment by TheTurkeyDev** [comment]
Relevant COM:Z from above log removing any possibly sensitive info

```
[20:11:10] [Server thread/INFO]: [COM_Zombies] Enabling COM_Zombies v2.3.210
[20:11:10] [Server thread/INFO]: [COM:Z] [COM_Zombies] Version info | MC: 1.21 | Bukkit: 1.21-130-b1b5d4c (MC: 1.21) & 1.21-R0.1-SNAPSHOT | CB: org.bukkit.craftbukkit
[20:11:10] [Server thread/INFO]: [COM:Z] [COM_Zombies]  Vault hook enabled!
[20:11:10] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: comz [2.3.210]
[20:11:10] [Server thread/INFO]: [COM:Z] [COM_Zombies] has been enabled!
...
[20:19:38] [Server thread/INFO]: User issued server command: /z end Apartments
[20:19:43] [Server thread/INFO]: User issued server command: /z reload
[20:19:43] [Server thread/INFO]: [COM_Zombies] Disabling COM_Zombies v2.3.210
[20:19:43] [Server thread/INFO]: [COM:Z] [COM_Zombies] has been disabled!
[20:19:43] [Server thread/INFO]: [COM_Zombies] Enabling COM_Zombies v2.3.210
[20:19:43] [Server thread/WARN]: Enabled plugin with unregistered ConfiguredPluginClassLoader COM_Zombies v2.3.210
[20:19:43] [Server thread/INFO]: [COM:Z] [COM_Zombies] Version info | MC: 1.21 | Bukkit: 1.21-130-b1b5d4c (MC: 1.21) & 1.21-R0.1-SNAPSHOT | CB: org.bukkit.craftbukkit
[20:19:43] [Server thread/INFO]: [Zombies] Kit Weapon:   is an invalid gun name!
[20:19:43] [Server thread/INFO]: [Zombies] Perk:   is an invalid perk name!
[20:19:43] [Server thread/INFO]: [COM:Z] [COM_Zombies]  Vault hook enabled!
[20:19:43] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: comz [2.3.210]
[20:19:43] [Server thread/INFO]: [COM:Z] [COM_Zombies] has been enabled!
[20:19:43] [Server thread/INFO]: [ CoM: Zombies ]  Done loading arenas!
[20:19:43] [Server thread/INFO]: [ CoM: Zombies ]  Done loading arenas!
...
[20:21:07] [Server thread/INFO]: User issued server command: /z addarena wilderness
[20:21:07] [Server thread/ERROR]: Command exception: /z addarena wilderness
org.bukkit.command.CommandException: Unhandled exception executing command 'z' in plugin COM_Zombies v2.3.210
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at comzombies-Universal-2.3.210 (1).jar/com.theprogrammingturkey.comz.commands.CreateArenaCommand.onCommand(CreateArenaCommand.java:48) ~[comzombies-Universal-2.3.210 (1).jar:?]
	at comzombies-Universal-2.3.210 (1).jar/com.theprogrammingturkey.comz.commands.CommandManager.onCommand(CommandManager.java:281) ~[comzombies-Universal-2.3.210 (1).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	... 27 more
...
[20:55:04] [Server thread/ERROR]: Command exception: /z editarena Apartments
org.bukkit.command.CommandException: Unhandled exception executing command 'z' in plugin COM_Zombies v2.3.210
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at comzombies-Universal-2.3.210 (1).jar/com.theprogrammingturkey.comz.commands.EditCommand.onCommand(EditCommand.java:41) ~[comzombies-Universal-2.3.210 (1).jar:?]
	at comzombies-Universal-2.3.210 (1).jar/com.theprogrammingturkey.comz.commands.CommandManager.onCommand(CommandManager.java:281) ~[comzombies-Universal-2.3.210 (1).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	... 27 more
```

**Comment by TheTurkeyDev** [comment]
@Dallasp95 What if you try to use commands after the server starts up without using the reload command?

**Comment by Dallasp95** [comment]
Last time i tried that it was still bugged. Wouldnt let me delete arenas.
And would get stuck inside an action; like it would say i cant do somthing
else because im stil in the proccess of another action, but also wouldnt
let me type cancel or done to cancel the other action.

Altho as we speak i am trying somthing (which i thought i did already) but,
am going to see if i can get it running again

**Comment by TheTurkeyDev** [comment]
Appears tp be fixed in the newest versions of the plugin
